#ifndef SERVERSIDEPLUGIN_GLOBAL_H
#define SERVERSIDEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVERSIDEPLUGIN_LIBRARY)
#  define SERVERSIDEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVERSIDEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVERSIDEPLUGIN_GLOBAL_H
